language: python
python:
  - "2.7"
install:
  - pip install flake8
script:
  - flake8
  - nosetests -v tests
deploy:
  provider: pypi
  user: wg_webqaa
  password:
    secure: Yi797XDs45RpNMiAhzNWrtk4c19JP1LtnSzvDQ/8pqiPdRurveEqUFvMrlaQh1HytwuafgJ/iM1QwQ6KNoY25NmYOK1XCrbdK01MFrH54QRsT0DiS59W/I8CGH/rXd4bRXNHwLn3flwHIWYTLsK9PiIpZt9o7heiE6Ihlxpv5LQ=
  on:
    tags: true
    distributions: sdist
    repo: wgnet/grail
